"""added policies

Revision ID: 0478d4adcc59
Revises: e5c0a708cbb9
Create Date: 2026-03-27 01:36:47.014126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0478d4adcc59'
down_revision: Union[str, Sequence[str], None] = 'e5c0a708cbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_rates_id'), table_name='insurance_rates')
    op.drop_table('insurance_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crop_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('base_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('insurance_rates_pkey'))
    )
    op.create_index(op.f('ix_insurance_rates_id'), 'insurance_rates', ['id'], unique=False)
    # ### end Alembic commands ###
