"""Add scheme_id to policy

Revision ID: 08e4f4fa2b42
Revises: 8bcaad1af3f3
Create Date: 2026-03-23 10:13:00.172645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e4f4fa2b42'
down_revision: Union[str, Sequence[str], None] = '8bcaad1af3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('scheme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'policies', 'schemes', ['scheme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'scheme_id')
    # ### end Alembic commands ###
