"""create_farms_table

Revision ID: 18f5a08c44c6
Revises: 663e3b44c42b
Create Date: 2026-02-21 20:58:43.808761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '18f5a08c44c6'
down_revision: Union[str, Sequence[str], None] = '663e3b44c42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure PostGIS extension is enabled before creating tables with spatial types
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(), nullable=True),
    sa.Column('crop_type', sa.String(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, spatial_index=False), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_farms_boundary', 'farms', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_index('idx_farms_boundary', table_name='farms', postgresql_using='gist')
    op.drop_table('farms')
    # ### end Alembic commands ###
