"""added schemes table

Revision ID: 8bcaad1af3f3
Revises: 18f5a08c44c6
Create Date: 2026-03-23 09:38:39.601523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcaad1af3f3'
down_revision: Union[str, Sequence[str], None] = '18f5a08c44c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_farms_boundary'), table_name='farms', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_farms_boundary'), 'farms', ['boundary'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
