"""added table

Revision ID: a0051e8ed6d8
Revises: 0478d4adcc59
Create Date: 2026-03-27 10:24:32.754177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0051e8ed6d8'
down_revision: Union[str, Sequence[str], None] = '0478d4adcc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type manually if it doesn't exist
    disaster_type_enum = postgresql.ENUM('Flood', 'Drought', 'Pest Attack', 'Cyclone', 'Hailstorm', 'Fire', name='disastertype')
    disaster_type_enum.create(op.get_bind())

    op.add_column('claims', sa.Column('is_settled', sa.Boolean(), nullable=False))
    op.alter_column('claims', 'disaster_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Flood', 'Drought', 'Pest Attack', 'Cyclone', 'Hailstorm', 'Fire', name='disastertype'),
               existing_nullable=False,
               postgresql_using="disaster_type::disastertype")
    op.alter_column('claims', 'affected_area',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="affected_area::double precision")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'affected_area',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="affected_area::varchar")
    op.alter_column('claims', 'disaster_type',
               existing_type=sa.Enum('Flood', 'Drought', 'Pest Attack', 'Cyclone', 'Hailstorm', 'Fire', name='disastertype'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="disaster_type::varchar")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
